spring:
    application:
        name: spring-cloud-config-server
    profiles:
        active: @activatedProperties@
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    main:
        allow-bean-definition-overriding: true
server:
    port: 8888