spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/UbaidurRehman1/public-repo.git
                    skip-ssl-validation: true
                    timeout: 60