server:
  port: 10000
  
logging:
  level:
    web: DEBUG
    'dev.ubaid': DEBUG
    'org.springframework.cloud': DEBUG
    
spring:
  cloud:
    gateway:
      routes:
        - id: spa-route
          uri: forward:/index.html
          predicates:
            - Path=/(!services/**),/**