apiVersion: v1
kind: PersistentVolume
metadata:
    name: auth-db-pv
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 20Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/mnt/pv/authdb"
---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 20Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/mnt/pv/db"
---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: elasticsearch-pv
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 20Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/mnt/pv/elasticsearch"
---
