export const POPULATE_COUNTRIES_START = 'POPULATE_COUNTRIES_START';
export const POPULATE_COUNTRIES_FINISHED = 'POPULATE_COUNTRIES_FINISHED';
export const POPULATE_COUNTRIES_ERROR = 'POPULATE_COUNTRIES_ERROR';
