export const POPULATE_COUNTRIES_START = 'POPULATE_COUNTRIES_START';
export const POPULATE_COUNTRIES_FINISHED = 'POPULATE_COUNTRIES_FINISHED';
export const POPULATE_COUNTRIES_ERROR = 'POPULATE_COUNTRIES_ERROR';

export const SELECT_TO_COUNTRY = 'SELECT_TO_COUNTRY';
export const SELECT_FROM_COUNTRY = 'SELECT_FROM_COUNTRY';

export const CONVERT_CURRENCY_START = 'CONVERT_CURRENCY_START';
export const CONVERT_CURRENCY_COMPLETE = 'CONVERT_CURRENCY_COMPLETE';
export const CONVERT_CURRENCY_ERROR = 'CONVERT_CURRENCY_ERROR';

export const ADD_ACCESS_TOKEN = 'ADD_ACCESS_TOKEN';
