version: "3.8"
services:
  api-gateway:
    image: ghcr.io/ubaid4j/cloud-native-app-spring-boot/api-gateway:0.0.3-snapshot
    container_name: api-gateway
    ports:
      - "127.0.0.1:40000:80"
    healthcheck:
      test: "bash /health-check.sh"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./api-gateway/health-check.sh:/health-check.sh
      - ./api-gateway/application-prod.yml:/workspace/config/application-prod.yml