FROM ubaidurehman/3cn-parent:0.0.1-SNAPSHOT as build
LABEL maintainer="urehman.bese16seecs@seecs.edu.pk"
VOLUME /tmp
WORKDIR /
ADD . .
RUN mvn clean install -DskipTests

FROM openjdk:16-jdk-alpine
VOLUME /tmp
WORKDIR /
EXPOSE 8900
COPY --from=build /target/user-service-0.0.1-SNAPSHOT.jar service.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=dev","-jar","/service.jar"]
