ARG APP_VERSION
FROM ubaidurehman/3cn-parent:${APP_VERSION} as build
LABEL maintainer="urehman.bese16seecs@seecs.edu.pk"
VOLUME /tmp
WORKDIR /
ADD . .
RUN mvn clean install -DskipTests

FROM openjdk:17-slim
VOLUME /tmp
WORKDIR /
EXPOSE 5200
ARG APP_VERSION
COPY --from=build /target/currency-conversion-${APP_VERSION}.jar service.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=dev","-jar","/service.jar"]
