-- liquibase formatted sql
-- changeset  ubaid:18Oct2020_2009
-- comment populating db with  countries
insert into country_code(country, currency_name, currency_code, number) values('AFGHANISTAN', 'Afghani','AFN',971);
insert into country_code(country, currency_name, currency_code, number) values('ÅLAND ISLANDS', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('ALBANIA', 'Lek','ALL',008);
insert into country_code(country, currency_name, currency_code, number) values('ALGERIA', 'Algerian Dinar','DZD',012);
insert into country_code(country, currency_name, currency_code, number) values('AMERICAN SAMOA', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('ANDORRA', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('ANGOLA', 'Kwanza','AOA',973);
insert into country_code(country, currency_name, currency_code, number) values('ANGUILLA', 'East Caribbean Dollar','XCD',951);
insert into country_code(country, currency_name, currency_code, number) values('ANTARCTICA', 'No universal currency','',null);
insert into country_code(country, currency_name, currency_code, number) values('ANTIGUA AND BARBUDA', 'East Caribbean Dollar','XCD',951);
insert into country_code(country, currency_name, currency_code, number) values('ARGENTINA', 'Argentine Peso','ARS',032);
insert into country_code(country, currency_name, currency_code, number) values('ARMENIA', 'Armenian Dram','AMD',051);
insert into country_code(country, currency_name, currency_code, number) values('ARUBA', 'Aruban Florin','AWG',533);
insert into country_code(country, currency_name, currency_code, number) values('AUSTRALIA', 'Australian Dollar','AUD',036);
insert into country_code(country, currency_name, currency_code, number) values('AUSTRIA', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('AZERBAIJAN', 'Azerbaijanian Manat','AZN',944);
insert into country_code(country, currency_name, currency_code, number) values('BAHAMAS (THE)', 'Bahamian Dollar','BSD',044);
insert into country_code(country, currency_name, currency_code, number) values('BAHRAIN', 'Bahraini Dinar','BHD',048);
insert into country_code(country, currency_name, currency_code, number) values('BANGLADESH', 'Taka','BDT',050);
insert into country_code(country, currency_name, currency_code, number) values('BARBADOS', 'Barbados Dollar','BBD',052);
insert into country_code(country, currency_name, currency_code, number) values('BELARUS', 'Belarussian Ruble','BYN',933);
insert into country_code(country, currency_name, currency_code, number) values('BELGIUM', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('BELIZE', 'Belize Dollar','BZD',084);
insert into country_code(country, currency_name, currency_code, number) values('BENIN', 'CFA Franc BCEAO','XOF',952);
insert into country_code(country, currency_name, currency_code, number) values('BERMUDA', 'Bermudian Dollar','BMD',060);
insert into country_code(country, currency_name, currency_code, number) values('BHUTAN', 'Ngultrum','BTN',064);
insert into country_code(country, currency_name, currency_code, number) values('BHUTAN', 'Indian Rupee','INR',356);
insert into country_code(country, currency_name, currency_code, number) values('BOLIVIA (PLURINATIONAL STATE    OF)', 'Boliviano','BOB',068);
insert into country_code(country, currency_name, currency_code, number) values('BOLIVIA (PLURINATIONAL STATE    OF)', 'Mvdol','BOV',984);
insert into country_code(country, currency_name, currency_code, number) values('BONAIRE, SINT EUSTATIUS AND    SABA', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('BOSNIA AND HERZEGOVINA', 'Convertible Mark','BAM',977);
insert into country_code(country, currency_name, currency_code, number) values('BOTSWANA', 'Pula','BWP',072);
insert into country_code(country, currency_name, currency_code, number) values('BOUVET ISLAND', 'Norwegian Krone','NOK',578);
insert into country_code(country, currency_name, currency_code, number) values('BRAZIL', 'Brazilian Real','BRL',986);
insert into country_code(country, currency_name, currency_code, number) values('BRITISH INDIAN OCEAN    TERRITORY (THE)', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('BRUNEI DARUSSALAM', 'Brunei Dollar','BND',096);
insert into country_code(country, currency_name, currency_code, number) values('BULGARIA', 'Bulgarian Lev','BGN',975);
insert into country_code(country, currency_name, currency_code, number) values('BURKINA FASO', 'CFA Franc BCEAO','XOF',952);
insert into country_code(country, currency_name, currency_code, number) values('BURUNDI', 'Burundi Franc','BIF',108);
insert into country_code(country, currency_name, currency_code, number) values('CABO VERDE', 'Cabo Verde Escudo','CVE',132);
insert into country_code(country, currency_name, currency_code, number) values('CAMBODIA', 'Riel','KHR',116);
insert into country_code(country, currency_name, currency_code, number) values('CAMEROON', 'CFA Franc BEAC','XAF',950);
insert into country_code(country, currency_name, currency_code, number) values('CANADA', 'Canadian Dollar','CAD',124);
insert into country_code(country, currency_name, currency_code, number) values('CAYMAN ISLANDS (THE)', 'Cayman Islands Dollar','KYD',136);
insert into country_code(country, currency_name, currency_code, number) values('CENTRAL AFRICAN REPUBLIC    (THE)', 'CFA Franc BEAC','XAF',950);
insert into country_code(country, currency_name, currency_code, number) values('CHAD', 'CFA Franc BEAC','XAF',950);
insert into country_code(country, currency_name, currency_code, number) values('CHILE', 'Unidad de Fomento','CLF',990);
insert into country_code(country, currency_name, currency_code, number) values('CHILE', 'Chilean Peso','CLP',152);
insert into country_code(country, currency_name, currency_code, number) values('CHINA', 'Yuan Renminbi','CNY',156);
insert into country_code(country, currency_name, currency_code, number) values('CHRISTMAS ISLAND', 'Australian Dollar','AUD',036);
insert into country_code(country, currency_name, currency_code, number) values('COCOS (KEELING) ISLANDS (THE)', 'Australian Dollar','AUD',036);
insert into country_code(country, currency_name, currency_code, number) values('COLOMBIA', 'Colombian Peso','COP',170);
insert into country_code(country, currency_name, currency_code, number) values('COLOMBIA', 'Unidad de Valor Real','COU',970);
insert into country_code(country, currency_name, currency_code, number) values('COMOROS (THE)', 'Comoro Franc','KMF',174);
insert into country_code(country, currency_name, currency_code, number) values('CONGO (THE DEMOCRATIC    REPUBLIC OF THE)', 'Congolese Franc','CDF',976);
insert into country_code(country, currency_name, currency_code, number) values('CONGO (THE)', 'CFA Franc BEAC','XAF',950);
insert into country_code(country, currency_name, currency_code, number) values('COOK ISLANDS (THE)', 'New Zealand Dollar','NZD',554);
insert into country_code(country, currency_name, currency_code, number) values('COSTA RICA', 'Costa Rican Colon','CRC',188);
insert into country_code(country, currency_name, currency_code, number) values('CÔTE DIVOIRE', 'CFA Franc BCEAO','XOF',952);
insert into country_code(country, currency_name, currency_code, number) values('CROATIA', 'Kuna','HRK',191);
insert into country_code(country, currency_name, currency_code, number) values('CUBA', 'Peso Convertible','CUC',931);
insert into country_code(country, currency_name, currency_code, number) values('CUBA', 'Cuban Peso','CUP',192);
insert into country_code(country, currency_name, currency_code, number) values('CURAÇAO', 'Netherlands Antillean Guilder','ANG',532);
insert into country_code(country, currency_name, currency_code, number) values('CYPRUS', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('CZECH REPUBLIC (THE)', 'Czech Koruna','CZK',203);
insert into country_code(country, currency_name, currency_code, number) values('DENMARK', 'Danish Krone','DKK',208);
insert into country_code(country, currency_name, currency_code, number) values('DJIBOUTI', 'Djibouti Franc','DJF',262);
insert into country_code(country, currency_name, currency_code, number) values('DOMINICA', 'East Caribbean Dollar','XCD',951);
insert into country_code(country, currency_name, currency_code, number) values('DOMINICAN REPUBLIC (THE)', 'Dominican Peso','DOP',214);
insert into country_code(country, currency_name, currency_code, number) values('ECUADOR', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('EGYPT', 'Egyptian Pound','EGP',818);
insert into country_code(country, currency_name, currency_code, number) values('EL SALVADOR', 'El Salvador Colon','SVC',222);
insert into country_code(country, currency_name, currency_code, number) values('EL SALVADOR', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('EQUATORIAL GUINEA', 'CFA Franc BEAC','XAF',950);
insert into country_code(country, currency_name, currency_code, number) values('ERITREA', 'Nakfa','ERN',232);
insert into country_code(country, currency_name, currency_code, number) values('ESTONIA', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('ETHIOPIA', 'Ethiopian Birr','ETB',230);
insert into country_code(country, currency_name, currency_code, number) values('EUROPEAN UNION', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('FALKLAND ISLANDS (THE)    [MALVINAS]', 'Falkland Islands Pound','FKP',238);
insert into country_code(country, currency_name, currency_code, number) values('FAROE ISLANDS (THE)', 'Danish Krone','DKK',208);
insert into country_code(country, currency_name, currency_code, number) values('FIJI', 'Fiji Dollar','FJD',242);
insert into country_code(country, currency_name, currency_code, number) values('FINLAND', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('FRANCE', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('FRENCH GUIANA', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('FRENCH POLYNESIA', 'CFP Franc','XPF',953);
insert into country_code(country, currency_name, currency_code, number) values('FRENCH SOUTHERN TERRITORIES    (THE)', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('GABON', 'CFA Franc BEAC','XAF',950);
insert into country_code(country, currency_name, currency_code, number) values('GAMBIA (THE)', 'Dalasi','GMD',270);
insert into country_code(country, currency_name, currency_code, number) values('GEORGIA', 'Lari','GEL',981);
insert into country_code(country, currency_name, currency_code, number) values('GERMANY', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('GHANA', 'Ghana Cedi','GHS',936);
insert into country_code(country, currency_name, currency_code, number) values('GIBRALTAR', 'Gibraltar Pound','GIP',292);
insert into country_code(country, currency_name, currency_code, number) values('GREECE', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('GREENLAND', 'Danish Krone','DKK',208);
insert into country_code(country, currency_name, currency_code, number) values('GRENADA', 'East Caribbean Dollar','XCD',951);
insert into country_code(country, currency_name, currency_code, number) values('GUADELOUPE', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('GUAM', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('GUATEMALA', 'Quetzal','GTQ',320);
insert into country_code(country, currency_name, currency_code, number) values('GUERNSEY', 'Pound Sterling','GBP',826);
insert into country_code(country, currency_name, currency_code, number) values('GUINEA', 'Guinea Franc','GNF',324);
insert into country_code(country, currency_name, currency_code, number) values('GUINEA-BISSAU', 'CFA Franc BCEAO','XOF',952);
insert into country_code(country, currency_name, currency_code, number) values('GUYANA', 'Guyana Dollar','GYD',328);
insert into country_code(country, currency_name, currency_code, number) values('HAITI', 'Gourde','HTG',332);
insert into country_code(country, currency_name, currency_code, number) values('HAITI', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('HEARD ISLAND AND McDONALD    ISLANDS', 'Australian Dollar','AUD',036);
insert into country_code(country, currency_name, currency_code, number) values('HOLY SEE (THE)', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('HONDURAS', 'Lempira','HNL',340);
insert into country_code(country, currency_name, currency_code, number) values('HONG KONG', 'Hong Kong Dollar','HKD',344);
insert into country_code(country, currency_name, currency_code, number) values('HUNGARY', 'Forint','HUF',348);
insert into country_code(country, currency_name, currency_code, number) values('ICELAND', 'Iceland Krona','ISK',352);
insert into country_code(country, currency_name, currency_code, number) values('INDIA', 'Indian Rupee','INR',356);
insert into country_code(country, currency_name, currency_code, number) values('INDONESIA', 'Rupiah','IDR',360);
insert into country_code(country, currency_name, currency_code, number) values('INTERNATIONAL MONETARY FUND    (IMF) ', 'SDR (Special Drawing Right)','XDR',960);
insert into country_code(country, currency_name, currency_code, number) values('IRAN (ISLAMIC REPUBLIC OF)', 'Iranian Rial','IRR',364);
insert into country_code(country, currency_name, currency_code, number) values('IRAQ', 'Iraqi Dinar','IQD',368);
insert into country_code(country, currency_name, currency_code, number) values('IRELAND', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('ISLE OF MAN', 'Pound Sterling','GBP',826);
insert into country_code(country, currency_name, currency_code, number) values('ISRAEL', 'New Israeli Sheqel','ILS',376);
insert into country_code(country, currency_name, currency_code, number) values('ITALY', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('JAMAICA', 'Jamaican Dollar','JMD',388);
insert into country_code(country, currency_name, currency_code, number) values('JAPAN', 'Yen','JPY',392);
insert into country_code(country, currency_name, currency_code, number) values('JERSEY', 'Pound Sterling','GBP',826);
insert into country_code(country, currency_name, currency_code, number) values('JORDAN', 'Jordanian Dinar','JOD',400);
insert into country_code(country, currency_name, currency_code, number) values('KAZAKHSTAN', 'Tenge','KZT',398);
insert into country_code(country, currency_name, currency_code, number) values('KENYA', 'Kenyan Shilling','KES',404);
insert into country_code(country, currency_name, currency_code, number) values('KIRIBATI', 'Australian Dollar','AUD',036);
insert into country_code(country, currency_name, currency_code, number) values('KOREA (THE DEMOCRATIC    PEOPLE’S REPUBLIC OF)', 'North Korean Won','KPW',408);
insert into country_code(country, currency_name, currency_code, number) values('KOREA (THE REPUBLIC OF)', 'Won','KRW',410);
insert into country_code(country, currency_name, currency_code, number) values('KUWAIT', 'Kuwaiti Dinar','KWD',414);
insert into country_code(country, currency_name, currency_code, number) values('KYRGYZSTAN', 'Som','KGS',417);
insert into country_code(country, currency_name, currency_code, number) values('LAO PEOPLE’S DEMOCRATIC    REPUBLIC (THE)', 'Kip','LAK',418);
insert into country_code(country, currency_name, currency_code, number) values('LATVIA', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('LEBANON', 'Lebanese Pound','LBP',422);
insert into country_code(country, currency_name, currency_code, number) values('LESOTHO', 'Loti','LSL',426);
insert into country_code(country, currency_name, currency_code, number) values('LESOTHO', 'Rand','ZAR',710);
insert into country_code(country, currency_name, currency_code, number) values('LIBERIA', 'Liberian Dollar','LRD',430);
insert into country_code(country, currency_name, currency_code, number) values('LIBYA', 'Libyan Dinar','LYD',434);
insert into country_code(country, currency_name, currency_code, number) values('LIECHTENSTEIN', 'Swiss Franc','CHF',756);
insert into country_code(country, currency_name, currency_code, number) values('LITHUANIA', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('LUXEMBOURG', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('MACAO', 'Pataca','MOP',446);
insert into country_code(country, currency_name, currency_code, number) values('REPUBLIC OF NORTH MACEDONIA', 'Denar','MKD',807);
insert into country_code(country, currency_name, currency_code, number) values('MADAGASCAR', 'Malagasy Ariary','MGA',969);
insert into country_code(country, currency_name, currency_code, number) values('MALAWI', 'Kwacha','MWK',454);
insert into country_code(country, currency_name, currency_code, number) values('MALAYSIA', 'Malaysian Ringgit','MYR',458);
insert into country_code(country, currency_name, currency_code, number) values('MALDIVES', 'Rufiyaa','MVR',462);
insert into country_code(country, currency_name, currency_code, number) values('MALI', 'CFA Franc BCEAO','XOF',952);
insert into country_code(country, currency_name, currency_code, number) values('MALTA', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('MARSHALL ISLANDS (THE)', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('MARTINIQUE', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('MAURITANIA', 'Ouguiya','MRU',929);
insert into country_code(country, currency_name, currency_code, number) values('MAURITIUS', 'Mauritius Rupee','MUR',480);
insert into country_code(country, currency_name, currency_code, number) values('MAYOTTE', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('MEMBER COUNTRIES OF THE    AFRICAN DEVELOPMENT BANK GROUP', 'ADB Unit of Account','XUA',965);
insert into country_code(country, currency_name, currency_code, number) values('MEXICO', 'Mexican Peso','MXN',484);
insert into country_code(country, currency_name, currency_code, number) values('MEXICO', 'Mexican Unidad de Inversion (UDI)','MXV',979);
insert into country_code(country, currency_name, currency_code, number) values('MICRONESIA (FEDERATED STATES    OF)', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('MOLDOVA (THE REPUBLIC OF)', 'Moldovan Leu','MDL',498);
insert into country_code(country, currency_name, currency_code, number) values('MONACO', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('MONGOLIA', 'Tugrik','MNT',496);
insert into country_code(country, currency_name, currency_code, number) values('MONTENEGRO', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('MONTSERRAT', 'East Caribbean Dollar','XCD',951);
insert into country_code(country, currency_name, currency_code, number) values('MOROCCO', 'Moroccan Dirham','MAD',504);
insert into country_code(country, currency_name, currency_code, number) values('MOZAMBIQUE', 'Mozambique Metical','MZN',943);
insert into country_code(country, currency_name, currency_code, number) values('MYANMAR', 'Kyat','MMK',104);
insert into country_code(country, currency_name, currency_code, number) values('NAMIBIA', 'Namibia Dollar','NAD',516);
insert into country_code(country, currency_name, currency_code, number) values('NAMIBIA', 'Rand','ZAR',710);
insert into country_code(country, currency_name, currency_code, number) values('NAURU', 'Australian Dollar','AUD',036);
insert into country_code(country, currency_name, currency_code, number) values('NEPAL', 'Nepalese Rupee','NPR',524);
insert into country_code(country, currency_name, currency_code, number) values('NETHERLANDS (THE)', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('NEW CALEDONIA', 'CFP Franc','XPF',953);
insert into country_code(country, currency_name, currency_code, number) values('NEW ZEALAND', 'New Zealand Dollar','NZD',554);
insert into country_code(country, currency_name, currency_code, number) values('NICARAGUA', 'Cordoba Oro','NIO',558);
insert into country_code(country, currency_name, currency_code, number) values('NIGER (THE)', 'CFA Franc BCEAO','XOF',952);
insert into country_code(country, currency_name, currency_code, number) values('NIGERIA', 'Naira','NGN',566);
insert into country_code(country, currency_name, currency_code, number) values('NIUE', 'New Zealand Dollar','NZD',554);
insert into country_code(country, currency_name, currency_code, number) values('NORFOLK ISLAND', 'Australian Dollar','AUD',036);
insert into country_code(country, currency_name, currency_code, number) values('NORTHERN MARIANA ISLANDS    (THE)', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('NORWAY', 'Norwegian Krone','NOK',578);
insert into country_code(country, currency_name, currency_code, number) values('OMAN', 'Rial Omani','OMR',512);
insert into country_code(country, currency_name, currency_code, number) values('PAKISTAN', 'Pakistan Rupee','PKR',586);
insert into country_code(country, currency_name, currency_code, number) values('PALAU', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('PALESTINE, STATE OF', 'No universal currency','',null);
insert into country_code(country, currency_name, currency_code, number) values('PANAMA', 'Balboa','PAB',590);
insert into country_code(country, currency_name, currency_code, number) values('PANAMA', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('PAPUA NEW GUINEA', 'Kina','PGK',598);
insert into country_code(country, currency_name, currency_code, number) values('PARAGUAY', 'Guarani','PYG',600);
insert into country_code(country, currency_name, currency_code, number) values('PERU', 'Nuevo Sol','PEN',604);
insert into country_code(country, currency_name, currency_code, number) values('PHILIPPINES (THE)', 'Philippine Peso','PHP',608);
insert into country_code(country, currency_name, currency_code, number) values('PITCAIRN', 'New Zealand Dollar','NZD',554);
insert into country_code(country, currency_name, currency_code, number) values('POLAND', 'Zloty','PLN',985);
insert into country_code(country, currency_name, currency_code, number) values('PORTUGAL', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('PUERTO RICO', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('QATAR', 'Qatari Rial','QAR',634);
insert into country_code(country, currency_name, currency_code, number) values('RÉUNION', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('ROMANIA', 'Romanian Leu','RON',946);
insert into country_code(country, currency_name, currency_code, number) values('RUSSIAN FEDERATION (THE)', 'Russian Ruble','RUB',643);
insert into country_code(country, currency_name, currency_code, number) values('RWANDA', 'Rwanda Franc','RWF',646);
insert into country_code(country, currency_name, currency_code, number) values('SAINT BARTHÉLEMY', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('SAINT HELENA, ASCENSION AND    TRISTAN DA CUNHA', 'Saint Helena Pound','SHP',654);
insert into country_code(country, currency_name, currency_code, number) values('SAINT KITTS AND NEVIS', 'East Caribbean Dollar','XCD',951);
insert into country_code(country, currency_name, currency_code, number) values('SAINT LUCIA', 'East Caribbean Dollar','XCD',951);
insert into country_code(country, currency_name, currency_code, number) values('SAINT MARTIN (FRENCH PART)', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('SAINT PIERRE AND MIQUELON', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('SAINT VINCENT AND THE    GRENADINES', 'East Caribbean Dollar','XCD',951);
insert into country_code(country, currency_name, currency_code, number) values('SAMOA', 'Tala','WST',882);
insert into country_code(country, currency_name, currency_code, number) values('SAN MARINO', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('SAO TOME AND PRINCIPE', 'Dobra','STN',930);
insert into country_code(country, currency_name, currency_code, number) values('SAUDI ARABIA', 'Saudi Riyal','SAR',682);
insert into country_code(country, currency_name, currency_code, number) values('SENEGAL', 'CFA Franc BCEAO','XOF',952);
insert into country_code(country, currency_name, currency_code, number) values('SERBIA', 'Serbian Dinar','RSD',941);
insert into country_code(country, currency_name, currency_code, number) values('SEYCHELLES', 'Seychelles Rupee','SCR',690);
insert into country_code(country, currency_name, currency_code, number) values('SIERRA LEONE', 'Leone','SLL',694);
insert into country_code(country, currency_name, currency_code, number) values('SINGAPORE', 'Singapore Dollar','SGD',702);
insert into country_code(country, currency_name, currency_code, number) values('SINT MAARTEN (DUTCH PART)', 'Netherlands Antillean Guilder','ANG',532);
insert into country_code(country, currency_name, currency_code, number) values('SISTEMA UNITARIO DE    COMPENSACION REGIONAL DE PAGOS "SUCRE"', 'Sucre','XSU',994);
insert into country_code(country, currency_name, currency_code, number) values('SLOVAKIA', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('SLOVENIA', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('SOLOMON ISLANDS', 'Solomon Islands Dollar','SBD',090);
insert into country_code(country, currency_name, currency_code, number) values('SOMALIA', 'Somali Shilling','SOS',706);
insert into country_code(country, currency_name, currency_code, number) values('SOUTH AFRICA', 'Rand','ZAR',710);
insert into country_code(country, currency_name, currency_code, number) values('SOUTH GEORGIA AND THE SOUTH    SANDWICH ISLANDS', 'No universal currency','',null);
insert into country_code(country, currency_name, currency_code, number) values('SOUTH SUDAN', 'South Sudanese Pound','SSP',728);
insert into country_code(country, currency_name, currency_code, number) values('SPAIN', 'Euro','EUR',978);
insert into country_code(country, currency_name, currency_code, number) values('SRI LANKA', 'Sri Lanka Rupee','LKR',144);
insert into country_code(country, currency_name, currency_code, number) values('SUDAN (THE)', 'Sudanese Pound','SDG',938);
insert into country_code(country, currency_name, currency_code, number) values('SURINAME', 'Surinam Dollar','SRD',968);
insert into country_code(country, currency_name, currency_code, number) values('SVALBARD AND JAN MAYEN', 'Norwegian Krone','NOK',578);
insert into country_code(country, currency_name, currency_code, number) values('SWAZILAND', 'Lilangeni','SZL',748);
insert into country_code(country, currency_name, currency_code, number) values('SWEDEN', 'Swedish Krona','SEK',752);
insert into country_code(country, currency_name, currency_code, number) values('SWITZERLAND', 'WIR Euro','CHE',947);
insert into country_code(country, currency_name, currency_code, number) values('SWITZERLAND', 'Swiss Franc','CHF',756);
insert into country_code(country, currency_name, currency_code, number) values('SWITZERLAND', 'WIR Franc','CHW',948);
insert into country_code(country, currency_name, currency_code, number) values('SYRIAN ARAB REPUBLIC', 'Syrian Pound','SYP',760);
insert into country_code(country, currency_name, currency_code, number) values('TAIWAN (PROVINCE OF CHINA)', 'New Taiwan Dollar','TWD',901);
insert into country_code(country, currency_name, currency_code, number) values('TAJIKISTAN', 'Somoni','TJS',972);
insert into country_code(country, currency_name, currency_code, number) values('TANZANIA, UNITED REPUBLIC OF', 'Tanzanian Shilling','TZS',834);
insert into country_code(country, currency_name, currency_code, number) values('THAILAND', 'Baht','THB',764);
insert into country_code(country, currency_name, currency_code, number) values('TIMOR-LESTE', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('TOGO', 'CFA Franc BCEAO','XOF',952);
insert into country_code(country, currency_name, currency_code, number) values('TOKELAU', 'New Zealand Dollar','NZD',554);
insert into country_code(country, currency_name, currency_code, number) values('TONGA', 'Pa’anga','TOP',776);
insert into country_code(country, currency_name, currency_code, number) values('TRINIDAD AND TOBAGO', 'Trinidad and Tobago Dollar','TTD',780);
insert into country_code(country, currency_name, currency_code, number) values('TUNISIA', 'Tunisian Dinar','TND',788);
insert into country_code(country, currency_name, currency_code, number) values('TURKEY', 'Turkish Lira','TRY',949);
insert into country_code(country, currency_name, currency_code, number) values('TURKMENISTAN', 'Turkmenistan New Manat','TMT',934);
insert into country_code(country, currency_name, currency_code, number) values('TURKS AND CAICOS ISLANDS    (THE)', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('TUVALU', 'Australian Dollar','AUD',036);
insert into country_code(country, currency_name, currency_code, number) values('UGANDA', 'Uganda Shilling','UGX',800);
insert into country_code(country, currency_name, currency_code, number) values('UKRAINE', 'Hryvnia','UAH',980);
insert into country_code(country, currency_name, currency_code, number) values('UNITED ARAB EMIRATES (THE)', 'UAE Dirham','AED',784);
insert into country_code(country, currency_name, currency_code, number) values('UNITED KINGDOM OF GREAT    BRITAIN AND NORTHERN IRELAND (THE)', 'Pound Sterling','GBP',826);
insert into country_code(country, currency_name, currency_code, number) values('UNITED STATES MINOR OUTLYING    ISLANDS (THE)', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('UNITED STATES OF AMERICA    (THE)', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('UNITED STATES OF AMERICA    (THE)', 'US Dollar (Next day)','USN',997);
insert into country_code(country, currency_name, currency_code, number) values('URUGUAY', 'Uruguay Peso en Unidades Indexadas (URUIURUI)','UYI',940);
insert into country_code(country, currency_name, currency_code, number) values('URUGUAY', 'Peso Uruguayo','UYU',858);
insert into country_code(country, currency_name, currency_code, number) values('UZBEKISTAN', 'Uzbekistan Sum','UZS',860);
insert into country_code(country, currency_name, currency_code, number) values('VANUATU', 'Vatu','VUV',548);
insert into country_code(country, currency_name, currency_code, number) values('VENEZUELA (BOLIVARIAN    REPUBLIC OF)', 'Bolivar','VEF',937);
insert into country_code(country, currency_name, currency_code, number) values('VIET NAM', 'Dong','VND',704);
insert into country_code(country, currency_name, currency_code, number) values('VIRGIN ISLANDS (BRITISH)', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('VIRGIN ISLANDS (U.S.)', 'US Dollar','USD',840);
insert into country_code(country, currency_name, currency_code, number) values('WALLIS AND FUTUNA', 'CFP Franc','XPF',953);
insert into country_code(country, currency_name, currency_code, number) values('WESTERN SAHARA', 'Moroccan Dirham','MAD',504);
insert into country_code(country, currency_name, currency_code, number) values('YEMEN', 'Yemeni Rial','YER',886);
insert into country_code(country, currency_name, currency_code, number) values('ZAMBIA', 'Zambian Kwacha','ZMW',967);
insert into country_code(country, currency_name, currency_code, number) values('ZIMBABWE', 'Zimbabwe Dollar','ZWL',932);

